# MapR Kubernetes Container Storage Interface (CSI)

# Using the Kubernetes CSI for dynamic provisioning

# Provisioning: dynamic
# Container:    busybox

# Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: mapr-csi-dynamic-busybox
  labels:
    name: mapr-csi-dynamic-busybox

# Secret to authenticate with MapR Converged Data Platform
---
apiVersion: v1
kind: Secret
metadata:
  name: mapr-provisioner-secrets
  namespace: mapr-csi-dynamic-busybox
type: Opaque
data:
# base64 encoding: "echo -n '<username/password>' | base64" eg:
# echo -n 'mapr' | base64
  MAPR_CLUSTER_USER: bWFwcg==
  MAPR_CLUSTER_PASSWORD: bWFwcg==

# Ticket to authenticate with MapR Converged Data Platform
---
apiVersion: v1
kind: Secret
metadata:
  name: mapr-ticket-secret
  namespace: mapr-csi-dynamic-busybox
type: Opaque
# To create a Ticket:
# 1. maprlogin password -user mapr
# 2. echo -n $(cat /tmp/maprticket_####) | base64 -w 0
data:
  CONTAINER_TICKET: ZGVtby5tYXByLmNvbSBwNzc5VnNKN05xOWxmOU0vY3ZVbXJMek9WMHRlUWluaTZuRUFqZEpiU1BkaWZHVzlPRFFXQ1c5Z0R2NXFsTVlkOTZCQzhneWpTOWxwNGdrakkvL29QNStqRUNhNFlCeFRrb2RMcmdJaGZTeG1YOTBuRzJSRm9MSkJ1RFZKcDBObERYbkJEa3Q1OHAxRmpvKzNPKzMxb2lpZWtDMTYzb2VQc1ZXWm11Qm8zVEhjcmJaUmhJM2NVVmxVWC91b2xmL0lhOFBjM3o4TTgwV2FOM0RlOGJBVzUyeFdKSW9LZ1J1QWFzd1dFeWZVU3FpQ3lmQWgxMFI0Um9WUGVpMkIwZm5US2tyc3JqY3pIaXFnMWh5UE1SVm1QUzhaUUdTblU4OD0=

# StorageClass for MapR Converged Data Platform
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mapr-csi-dynamic-busybox-sc
  namespace: mapr-csi-dynamic-busybox
provisioner: com.mapr.csi-kdf
parameters:
    csiProvisionerSecretName: "mapr-provisioner-secrets"
    csiProvisionerSecretNamespace: "mapr-csi-dynamic-busybox"
    csiNodePublishSecretName: "mapr-ticket-secret"
    csiNodePublishSecretNamespace: "mapr-csi-dynamic-busybox"
    restServers: "172.16.4.233:8443"
    cldbHosts: "172.16.4.233"
    cluster: "demo.mapr.com"
    securityType: "secure"
    ticketSecretName: "mapr-ticket-secret"
    ticketSecretNamespace: "mapr-apps"
    maprSecretName: "mapr-provisioner-secrets"
    maprSecretNamespace: "mapr-apps"
    namePrefix: "busybox-csi"
    mountPrefix: "/busybox-csi"
    reclaimPolicy: "Retain"
    advisoryquota: "100M"

# PersistentVolumeClaim for MapR Converged Data Platform
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mapr-csi-dynamic-busybox-pvc
  namespace: mapr-csi-dynamic-busybox
spec:
  storageClassName: mapr-csi-dynamic-busybox-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300M
